#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Lua api for local.saastree.cn
LUCI_DEPENDS:=+luci-lib-aes

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
