#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Saier 6box
LUCI_DEPENDS:=@PACKAGE_luci-mod-admin +luci-app-base

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
