#
# Copyright (C) 2008-2014 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI 3.0 UI
LUCI_DEPENDS:=+luci-base +luci-app-saastree +iwinfo +ktpriv +netdata +apfreeqos +rp-pppoe-sniff +mwan3  +xfrpc

include ../../luci.mk

# call BuildPackage - OpenWrt buildroot signature
