#!/bin/sh /etc/rc.common

START=97

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

LB=/usr/bin/loadbalance
BASE_CNT=0
DISABLE=0

prepare_conf(){
		local cfg=$1
        config_get BASE_CNT "$cfg" "base_count" "0"
        config_get DISABLE "$cfg" "disabled" "0"
}


start() {
		config_load loadbalance
        config_foreach prepare_conf loadbalance
        [ "$DISABLE" -eq 1 ] && exit 1
        service_start $LB
}

stop() {
        service_stop $LB
}
